### ISSUE TITLE
add the slug and link to the slug on the AEP

### ISSUE THREAD

**Issue by toumorokoshi** [aep-dev/site-generator#33]
e.g. https://aep.dev/5 does not have a link to the slug at the top (e.g. to https://aep.dev/intro/). It would be great if there was such a slug.

below the title would be great:

![20241004_11h54m08s_grim](https://github.com/user-attachments/assets/d2a219f6-89c5-4026-ae7c-8b550f481752)

**Comment by toumorokoshi** [comment]
also we should include the number-based link (@earth2marsh has convinced me that we need a single URL for this with a permanent redirect for seo / analytics / idiomatic reasons).

**Comment by earth2marsh** [comment]
Closing in favor of the info panel issue (#34), as I think it supplants this? Please re-open if not.
